name: Stock Prophet Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 1-5'  # Run at midnight on weekdays

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Add environment secrets and CI flag
    env:
      ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      CI: 'true'  # Mark as CI environment
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-ci.txt ]; then 
          pip install -r requirements-ci.txt
        else 
          pip install -e .
        fi
        
    - name: Setup environment
      run: |
        bash github_setup.sh
        
    - name: Run all tests with CI optimizations
      run: |
        echo "Running Stock Prophet test suite in CI mode"
        python test_stock.py
      
    # If the main test passes, we're done - the test_stock.py file now handles all tests in CI mode
    # But for backward compatibility and extra confidence, we'll run individual tests too
        
    - name: Run additional tests for specific stocks
      if: success() || failure()  # Run even if previous step failed
      run: |
        echo "Testing Apple stock analysis"
        python test_stock.py AAPL
        echo "Testing NVIDIA stock analysis"
        python test_stock.py NVDA
      continue-on-error: true
        
    - name: Test strategy functionality
      if: success() || failure()  # Run even if previous step failed
      run: |
        # This will test all available strategies
        for strategy in rsi bollinger macd combined; do
          echo "Testing $strategy strategy"
          python -c "import main; main.set_user_strategy('test_user', '$strategy'); print(f'Successfully set strategy to {main.get_user_strategy(\"test_user\")}');"
        done
      continue-on-error: true
        
    - name: Run backtest test with shorter timeframe for CI
      if: success() || failure()  # Run even if previous step failed
      run: |
        echo "Testing backtesting functionality with AAPL (CI optimized)"
        python test_stock.py backtest AAPL combined 2024-02-14 2024-03-15 1d
      continue-on-error: true